name: API Contactos CI/CD

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_BASE_NAME: omar/contactosapi

jobs:
  API_Image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ContactosAPI
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build Docker NET image
        run: | 
          docker build --platform linux -t $IMAGE_BASE_NAME .

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: deploy imagen to hub
        run: |
          docker push $IMAGE_BASE_NAME:latest
