name: API Contactos CI/CD

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_BASE_NAME: omar/apicontactos

jobs:
  API_Image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ContactosAPI
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Looking for files
        run: ls -a
        
      - name: Build Docker NET image
        run: | 
          docker build --platform linux -t $IMAGE_BASE_NAME .
